modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "takeitslow"
version = "${version}"
displayName = "Take it Slow"
authors = "iGalaxy"
description = '''
Who needs sprinting anyways?
'''
#logoFile = ""

[[dependencies.takeitslow]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.takeitslow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.takeitslow]]
modId = "cloth_config"
mandatory = true
versionRange = "[10,11)"
ordering = "NONE"
side = "BOTH"